on:
  push:

jobs:
  nix:
    runs-on: local/x86_64-linux

    steps:
      - uses: actions/checkout@v4

      - name: nix build
        run: |
          nix build .#

  test:
    runs-on: local/x86_64-linux

    steps:
      - uses: actions/checkout@v4

      - run: |
          nix develop --command dune build

      - run: |
          nix develop --command dune test
